# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 11:16


from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('xml', models.TextField()),
            ],
        ),
    ]
