# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 11:49


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('xml', models.TextField()),
            ],
        ),
    ]
