# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 01:25


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('game_node', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treenode',
            name='games',
            field=models.ManyToManyField(to='graph.Game'),
        ),
        migrations.AddField(
            model_name='treenode',
            name='questions',
            field=models.ManyToManyField(through='graph.QuestionLink', to='graph.TreeNode'),
        ),
        migrations.AddField(
            model_name='questionlink',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='graph.TreeNode'),
        ),
        migrations.AddField(
            model_name='questionlink',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='graph.TreeNode'),
        ),
        migrations.AddField(
            model_name='user',
            name='root_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graph.TreeNode'),
        ),
    ]
